"""empty message

Revision ID: 1.4
Revises: 1.3
Create Date: 2024-05-13 20:13:24.727560

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1.4'
down_revision = '1.3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_balance', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=mysql.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('card_image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('is_purchased', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('purchases_ibfk_1', type_='foreignkey')
        batch_op.drop_column('download_url')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('download_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key('purchases_ibfk_1', 'customers', ['user_id'], ['id'])
        batch_op.drop_column('is_purchased')
        batch_op.drop_column('price')
        batch_op.drop_column('description')
        batch_op.drop_column('card_image_path')
        batch_op.drop_column('file_path')

    with op.batch_alter_table('global_balance', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.BigInteger(),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
