"""empty message

Revision ID: 1.8
Revises: 1.7
Create Date: 2024-05-25 04:16:29.843187

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1.8'
down_revision = '1.7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_submission_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('student_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('demo_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo_submissions')
    op.drop_table('demo_submission_settings')
    # ### end Alembic commands ###
