"""empty message

Revision ID: 01b62df28846
Revises: 
Create Date: 2024-04-27 00:55:50.596659

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01b62df28846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('course_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('fk_course', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.create_index(batch_op.f('ix_calendar_id'), ['id'], unique=True)

    with op.batch_alter_table('course_programs', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('course_programs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('homework_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('student_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('homework_submissions_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('homework_submissions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['reviewer_id'], ['id'])
        batch_op.create_foreign_key(None, 'homeworks', ['homework_id'], ['id'])

    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('homeworks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('stream_emails', schema=None) as batch_op:
        batch_op.drop_index('stream_email_idx')
        batch_op.create_index(batch_op.f('ix_stream_emails_id'), ['id'], unique=False)
        batch_op.create_unique_constraint(None, ['stream_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=True)

    with op.batch_alter_table('zoom', schema=None) as batch_op:
        batch_op.drop_index('email_unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zoom', schema=None) as batch_op:
        batch_op.create_index('email_unique', ['email'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    with op.batch_alter_table('stream_emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_stream_emails_id'))
        batch_op.create_index('stream_email_idx', ['id', 'email'], unique=True)

    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('homeworks_ibfk_1', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False)

    with op.batch_alter_table('homework_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('homework_submissions_ibfk_2', 'customers', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('homework_submissions_ibfk_1', 'homeworks', ['homework_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False)
        batch_op.drop_column('reviewer_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('course_programs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('course_programs_ibfk_1', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False)

    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_id'))
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_course', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
