"""empty message

Revision ID: 1.0
Revises: 
Create Date: 2024-04-27 13:57:36.628169

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '1.0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=True)

    with op.batch_alter_table('zoom', schema=None) as batch_op:
        batch_op.drop_index('email_unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zoom', schema=None) as batch_op:
        batch_op.create_index('email_unique', ['email'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    # ### end Alembic commands ###
