"""empty message

Revision ID: 1.2
Revises: 1.1
Create Date: 2024-05-08 11:57:19.273408

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import String, Integer, Float, Text
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '1.2'
down_revision = '1.1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False), sa.Column('description', sa.Text(),
                                                                                         nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_table('achievement_criteria', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('achievement_id', sa.Integer(), nullable=False), sa.Column('criteria_type', sa.String(length=50), nullable=False),
                    sa.Column('threshold', sa.Float(), nullable=False), sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
                    sa.PrimaryKeyConstraint('id'))

    achievements_table = table('achievements',
        column('id', Integer),
        column('title', String),
        column('description', Text)
    )

    achievement_criteria_table = table('achievement_criteria', column('id', Integer), column('achievement_id', Integer),
                                       column('criteria_type', String), column('threshold', Float))

    op.bulk_insert(achievements_table,
        [
            {'title': "Начинатель", 'description': "Ты как первый бит на рейве — все знают, что это только начало."},
            {'title': "Бас менеджер", 'description': "Басы уже качают, но до полного контроля над танцполом не хватает опыта!"},
            {'title': "Снеер (МВД - министерство внутреннего драма)", 'description': "Твои снейры отзываются эхом в сердцах фанатов, а сабы тишиной в сайд сигналах! Когда вас много - вы СнеерА!"},
            {'title': "paDAWan Виртуоз", 'description': "Твоя музыка — это путешествие в другую галактику, где правят басы и транзиент шейперы."},
            {'title': "Академик", 'description': "Твои сабы заставляют землю дрожать — продолжай!"}
        ]
    )

    op.bulk_insert(achievement_criteria_table,
        [
            {'achievement_id': 1, 'criteria_type': 'average_grade', 'threshold': 3.0},
            {'achievement_id': 2, 'criteria_type': 'average_grade', 'threshold': 3.5},
            {'achievement_id': 3, 'criteria_type': 'average_grade', 'threshold': 4.0},
            {'achievement_id': 4, 'criteria_type': 'average_grade', 'threshold': 4.5},
            {'achievement_id': 5, 'criteria_type': 'average_grade', 'threshold': 4.8}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement_criteria')
    op.drop_table('achievements')
    # ### end Alembic commands ##
