"""empty message

Revision ID: 1.3
Revises: 1.2
Create Date: 2024-05-11 00:06:56.504639

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1.3'
down_revision = '1.2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('download_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.drop_column('title')

    op.drop_table('purchase')
    op.drop_table('global_balance')
    # ### end Alembic commands ###
